"""
Provide mappings for genre extractor.
"""
from src.enums.book import BookGenre


GENRES_MAPPING = {
    BookGenre.FANTASY: ["фентезі", "фантазі", "фентазі"],
    BookGenre.SCIENCE_FICTION: ["фантастика", "наукова фантастика", "sci-fi", "сай-фай"],
    BookGenre.THRILLER: ["трилер", "трилери"],
    BookGenre.HORROR: ["жахи", "хоррор", "горор"],
    BookGenre.DETECTIVE: ["детектив", "детективи", "детективний роман"],
    BookGenre.ACTION: ["бойовик", "екшн", "action"],
    BookGenre.ADVENTURE: ["пригоди", "пригодницький роман"],
    BookGenre.HISTORICAL_NOVEL: ["історичний роман", "історична проза", "історична література"],
    BookGenre.ROMANCE: ["любовний роман", "романтика", "романтична література", "мелодрама", "романтична проза"],
    BookGenre.DRAMA: ["драма"],
    BookGenre.COMEDY: ["комедія", "гумор", "сатира"],
    BookGenre.MYSTICISM: ["містика", "містичний роман"],
    BookGenre.FOLKLORE: ["фольклор", "казки", "легенди"],
    BookGenre.POETRY: ["поезія", "вірші", "лірика"],
    BookGenre.PROSE: ["проза", "художня проза"],
    BookGenre.CLASSIC_LITERATURE: ["класична література", "класика"],
    BookGenre.CONTEMPORARY_LITERATURE: ["сучасна література", "сучасна проза"],
    BookGenre.BIOGRAPHY: ["біографія", "автобіографія", "мемуари"],
    BookGenre.PSYCHOLOGICAL_PROSE: ["психологічна проза", "психологічний роман"],
    BookGenre.PHILOSOPHICAL_PROSE: ["філософська проза", "філософський роман"],
    BookGenre.SOCIAL_PROSE: ["соціальна проза", "соціальний роман"],
    BookGenre.POST_APOCALYPTIC: ["постапокаліпсис", "апокаліпсис"],
    BookGenre.DYSTOPIA: ["дистопія", "антиутопія"],
    BookGenre.UTOPIA: ["утопія"],
    BookGenre.CYBERPUNK: ["кіберпанк"],
    BookGenre.STEAMPUNK: ["стімпанк"],
    BookGenre.SPACE_OPERA: ["космоопера", "космічна опера"],
    BookGenre.MILITARY_FICTION: ["бойова фантастика", "військова фантастика"],
    BookGenre.URBAN_FANTASY: ["міське фентезі", "сучасне фентезі"],
    BookGenre.EPIC_FANTASY: ["епічне фентезі", "високе фентезі"],
    BookGenre.DARK_FANTASY: ["темне фентезі"],
    BookGenre.PARANORMAL_ROMANCE: ["паранормальний роман", "паранормальна романтика"],
    BookGenre.SPY_NOVEL: ["шпигунський роман", "шпигунський трилер"],
    BookGenre.POLITICAL_THRILLER: ["політичний трилер"],
    BookGenre.CRIME_NOVEL: ["кримінальний роман", "кримінал"],
    BookGenre.NOIR: ["нуар"],
    BookGenre.WESTERN: ["вестерн"],
    BookGenre.FAMILY_SAGA: ["сімейна сага", "сага"],
    BookGenre.EROTICA: ["еротика", "еротичний роман"],
    BookGenre.YOUNG_ADULT: ["young adult", "ya", "молодіжна література", "підліткова література"],
    BookGenre.CHILDREN_LITERATURE: ["дитяча література", "дитячі книги"],
    BookGenre.JOURNALISM: ["публіцистика", "есе", "нарис"],
    BookGenre.ACADEMIC_LITERATURE: ["наукова література", "наукові праці"],
    BookGenre.POPULAR_SCIENCE: ["популярна наука"],
    BookGenre.SELF_HELP: ["самодопомога", "саморозвиток", "мотивація"],
    BookGenre.BUSINESS: ["бізнес", "бізнес-література"],
    BookGenre.PSYCHOLOGY: ["психологія"],
    BookGenre.PHILOSOPHY: ["філософія"],
    BookGenre.RELIGION: ["релігія", "релігійна література"],
    BookGenre.TRAVEL: ["подорожі", "тревелог"],
    BookGenre.COOKING: ["кулінарія", "кулінарна книга"],
    BookGenre.GRAPHIC_NOVEL: ["графічний роман", "комікс", "манга"],
}
GENRES_NOISE_WORDS = {
    "книги", "книга", "жанру", "жанр", "твори", "твір",
    "та", "і", "й", "або", "в", "у", "на", "про", "для"
}
